version: '3.1'
services:
  web:
    image: odoo:16.0
    container_name: odoo
    networks:
      - ic-group
    depends_on:
      - db
    ports:
      - "30600:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /var/odoo/config:/etc/odoo
      - /var/odoo/addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password

  db:
    image: postgres:15
    container_name: postgresql
    networks:
      - ic-group
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    networks:
      - ic-group
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - 30601:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json

  ic-webapp:
    image: erickmpene/ic-group:v1
    container_name: ic-webapp
    networks:
      - ic-group
    ports:
      - 80:8080
    volumes:
      - ic-webapp-data:/opt
    environment:
      - "ODOO_URL=http://192.168.1.180:30600/"
      - "PGADMIN_URL=http://192.168.1.180:30601/"

volumes:
  odoo-web-data:
  odoo-db-data:
  pgadmin-data:
  ic-webapp-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
networks:
  ic-group:
    driver: bridge

