version: '3.1'
services:
  ic-webapp:
    image: erickmpene/ic-group:v1
    container_name: ic-webapp
    networks:
      - ic-group
    ports:
      - 80:8080
    volumes:
      - ic-webapp-data:/opt
    environment:
      - "ODOO_URL=http://192.168.1.180:30600/"
      - "PGADMIN_URL=http://192.168.1.180:30601/"
volumes:
  ic-webapp-data:
networks:
  ic-group:
    driver: bridge

