version: '3.1'
services:
  web:
    image: odoo:16.0
    container_name: odoo
    networks:
      - ic-group
    depends_on:
      - db
    ports:
      - "30600:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /var/odoo/config:/etc/odoo
      - /var/odoo/addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password

  db:
    image: postgres:15
    container_name: postgresql
    networks:
      - ic-group
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    ports:
      - "5432:5432"

networks:
  ic-group:
volumes:
  odoo-web-data:
  odoo-db-data:
secrets:
  postgresql_password:
    file: odoo_pg_pass