version: '3.1'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    networks:
      - ic-group
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - 30601:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json

volumes:
  pgadmin-data:

networks:
  ic-group: