apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: icgroup
  labels:
    app: postgresql
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      env: prod
  template:
    metadata:
      labels:
        app: postgresql
        env: prod
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          resources:
            limits:
              memory: "700Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_DB
              valueFrom: 
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_DB 
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_USER 
            - name: PGDATA
              valueFrom: 
                secretKeyRef:
                  name: postgresql-secret
                  key: PGDATA
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD 
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data-postgresql
              mountPath: /var/lib/postgresql/data/pgdata
      volumes: 
        - name: data-postgresql
          persistentVolumeClaim:
            claimName: pvc-postgresql
