apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: icgroup
  labels:
    env: prod
spec:
   selector:
      app: postgresql
   type: ClusterIP
   ports:
      - port: 5432
        targetPort: 5432
