apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: prod
    app: ic-webapp
  name: ic-webapp
  namespace: icgroup
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: ic-webapp
      env: prod

  template:
    metadata:
      labels:
        app: ic-webapp
        env: prod
    spec:
      containers:
      - image: erickmpene/ic-group:v1 
        name: ic-webapp
        env:
        - name: ODOO_URL
          value: http://192.168.1.160:30600/
        - name: PGADMIN_URL
          value: http://192.168.1.160:30601/
        ports:
        - containerPort: 80
          name: ic-webapp

