apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: icgroup
  labels:
    env: prod
type: Opaque 
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: odoo
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_PASSWORD: MyStrongPassWord

---

apiVersion: v1
kind: Secret
metadata:
  name: odoo-secret
  namespace: icgroup
  labels:
    env: prod
type: Opaque 
stringData:
  HOST: postgresql-service
  PORT: "5432"
  USER: odoo
  PASSWORD: MyStrongPassWord

---

apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: icgroup
  labels:
    env: prod
type: Opaque 
stringData:
  PGADMIN_DEFAULT_EMAIL: user@domain.com
  PGADMIN_DEFAULT_PASSWORD: SuperSecret
