apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-configmap
  namespace: icgroup
  labels:
    env: prod 
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Odoo DATABASE",
          "Group": "Group Odoo",
          "Port": 5432,
          "Username": "odoo",
          "Host": "postgresql-service.icgroup.svc.cluster.local",
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres" 
        }
      }
    }
