apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pgadmin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: icgroup
  hostPath:
    path: /data/pgadmin
  




