apiVersion: v1
kind: Service
metadata:
   name: pgadmin-service
   namespace: icgroup
   labels:
     env: prod
spec:
   selector:
      app: pgadmin
   type: NodePort
   ports:
      - port: 80
        targetPort: 80
        nodePort: 30601