apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-odoo-data-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: icgroup3
  hostPath:
    path: /data/odoo/data


--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-odoo-data-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: icgroup3
  hostPath:
    path: /data/odoo/config
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-odoo-data-addons
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: icgroup3
  hostPath:
    path: /data/odoo/addons