apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-data-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: icgroup3
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-data-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: icgroup3
  resources:
    requests:
      storage: 10Gi


--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-data-addons
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: icgroup3
  resources:
    requests:
      storage: 10Gi