apiVersion: v1
kind: Service
metadata:
   name: odoo-service
   namespace: icgroup
spec:
   selector:
      app: odoo
   type: NodePort
   ports:
      - port: 8069
        targetPort: 8069
        nodePort: 30600