---
# - name: Update System
#   yum:
#     name: "*"
#     state: latest

- name: Install prerequisites
  apt:
    update_cache: yes
    name: ['nano', 'tree', 'python3-pip']
    state: present
  when: ansible_distribution == "Ubuntu"

# - name: Install pre-requisite packages
#   yum:
#     name: "{{ item }}"
#     state: present
#   loop:
#     - yum-utils
#     - device-mapper-persistent-data
#     - lvm2
#     - python3
  
- name: download pip script
  get_url:
    url: https://bootstrap.pypa.io/pip/3.6/get-pip.py
    dest: /tmp/get-pip.py
- name: install python-pip
  command: python3 /tmp/get-pip.py
  ignore_errors: yes

- name: Install docker python
  pip:
    name: docker-py
    executable: /usr/local/bin/pip3




 
